# Lecture 15: Numpy 

__Reading Material:__

- [Numpy tutorial](https://docs.scipy.org/doc/numpy-1.15.0/user/quickstart.html)
- generate and manipulate arrays with NumPy. 
- [Matplotlib tutorial](https://matplotlib.org/tutorials/introductory/images.html)
- create basic plots with matplotlib.




In [1]:
import numpy as np
import math
import matplotlib.pyplot as plt
%matplotlib inline

A reasonably Pythonic way of plotting the $\sin$ function without using NumPy explicity...

In [2]:
n_points = 100

delta = 4*math.pi/(n_points-1)
x = [delta*i for i in range(n_points)]
y = [math.sin(x_i) for x_i in x]
#print x
#print y
plt.plot(x, y,'-ro')

AttributeError: 'module' object has no attribute 'to_rgba'

In [3]:
#plt.plot(x, y,'-bo')
#plt.plot(x, y,'bo')
plt.plot(x, y)

AttributeError: 'module' object has no attribute 'to_rgba'

Generating the x-points using NumPy...

In [4]:
n_points = 100
x = np.linspace(0, 4*np.pi, n_points)
print x
print type(x)

[  0.           0.12693304   0.25386607   0.38079911   0.50773215
   0.63466518   0.76159822   0.88853126   1.01546429   1.14239733
   1.26933037   1.3962634    1.52319644   1.65012947   1.77706251
   1.90399555   2.03092858   2.15786162   2.28479466   2.41172769
   2.53866073   2.66559377   2.7925268    2.91945984   3.04639288
   3.17332591   3.30025895   3.42719199   3.55412502   3.68105806
   3.8079911    3.93492413   4.06185717   4.1887902    4.31572324
   4.44265628   4.56958931   4.69652235   4.82345539   4.95038842
   5.07732146   5.2042545    5.33118753   5.45812057   5.58505361
   5.71198664   5.83891968   5.96585272   6.09278575   6.21971879
   6.34665183   6.47358486   6.6005179    6.72745093   6.85438397
   6.98131701   7.10825004   7.23518308   7.36211612   7.48904915
   7.61598219   7.74291523   7.86984826   7.9967813    8.12371434
   8.25064737   8.37758041   8.50451345   8.63144648   8.75837952
   8.88531256   9.01224559   9.13917863   9.26611167   9.3930447
   9.519977

Totally missing the point of NumPy arrays:

In [5]:
y = np.zeros(len(x))
for i, x_i in enumerate(x):
    y[i] = np.sin(x_i)
plt.plot(x,y)

AttributeError: 'module' object has no attribute 'to_rgba'

The correct approach:

In [6]:
y = np.sin(x)
print type(y)
print len(y), len(x)
plt.plot(x, y)

<type 'numpy.ndarray'>
100 100


AttributeError: 'module' object has no attribute 'to_rgba'

In [7]:
plt.plot(x, np.cos(x),'r-', x, 2*np.sin(x),'b')

AttributeError: 'module' object has no attribute 'to_rgba'

I cannot think of a situation for which iterating over a NumPy array is the right thing to do. If you ever think you need to do this, think again. 

Get comfortable _vectorizing_ your scientific computing code: perform operations on entire arrays compactly using NumPy.

In [8]:
plt.plot(x, y, 'r-.')
plt.xlabel("x-coordinate")
plt.ylabel("y-coordinate")
plt.title("y(x) = sin(x)")

AttributeError: 'module' object has no attribute 'to_rgba'

Fancy use of `matplotlib` is not important for the class; I just wanted to show you what you _can_ do. I don't memorize this stuff; I look up what I want to do when I need it.

In [9]:
plt.rc('text', usetex=True)
plt.rc('font', family='serif')
plt.rc('font', size = 16)
plt.plot(x, y, x, np.cos(x))
plt.xlabel("$x$-coordinate") # supports LaTeX, if you know it
plt.ylabel("$y$-coordinate")
plt.title("$y(x) = f(x)$")
plt.legend(("$f(x) = \sin(x)$", "$f(x) = \cos(x)$"), bbox_to_anchor = (1,1))

AttributeError: 'module' object has no attribute 'to_rgba'

In [10]:
x = np.arange(24)
print x
print x.shape
print x.ndim
print x.dtype

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
1
int64


In [11]:
x = np.arange(24)
print x.shape
y = x.reshape((24,1))
print y.shape
print x.ndim, y.ndim
print x
print y

(24,)
(24, 1)
1 2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [12]:
y = x.reshape((4,6)) # 4 rows, 6 columns
print y
print y.shape
print y.ndim

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
(4, 6)
2


In [13]:
z = x.reshape((2,3,-1)) # 2 pages, 3 rows, as many columns as needed to preserve the number of elements
print z.ndim

3


In [14]:
#z = x.reshape((2,3,30)) # valueError
# z = x.reshape((-1,-1,4)) # this does not work
print z

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


General rule: when specifying the shape of an array, columns is always last. Rows is second to last. "Pages" is third to last. And so on.

Caution: for efficiency, many NumPy operations avoid copying data. They just give you different _views_ of the underlying data.

In [15]:
print x
print y
print z

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [16]:
x[11] = 999
print x
print y
print z

[  0   1   2   3   4   5   6   7   8   9  10 999  12  13  14  15  16  17
  18  19  20  21  22  23]
[[  0   1   2   3   4   5]
 [  6   7   8   9  10 999]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
[[[  0   1   2   3]
  [  4   5   6   7]
  [  8   9  10 999]]

 [[ 12  13  14  15]
  [ 16  17  18  19]
  [ 20  21  22  23]]]


<h3>Multidimensional Indexing:</h3> <br>
As with shapes, the column index goes last, the row index goes second to last, the "page" goes third to last, etc...

In [17]:
z[1,2,0]

20

<h3>Slicing:</h3> <br>
Slicing works the same way as it did with lists.

In [18]:
y = x[1:8:2] # slicing
print y

[1 3 5 7]


Except that it creates a _view_. It does not copy the data.

In [19]:
y[:] = 0
print x

[  0   0   2   0   4   0   6   0   8   9  10 999  12  13  14  15  16  17
  18  19  20  21  22  23]


In [20]:
x = np.array([[1,2],[2,3],[3,4]])
y = x.copy()
print "x=",x
print "y=",y
y[0] = 100
print "x=",x
print "y=",y

x= [[1 2]
 [2 3]
 [3 4]]
y= [[1 2]
 [2 3]
 [3 4]]
x= [[1 2]
 [2 3]
 [3 4]]
y= [[100 100]
 [  2   3]
 [  3   4]]


You need to be explicit if you really need to copy data; you use the `copy` method. But try to avoid it.

<h3>Fancy Indexing:</h3> <br>
Boolean masks are a really powerful tool for manipulating arrays.

In [21]:
# fancy indexing creates a copy
x = np.arange(5)
y = x[[0,2]]
print y
y[0] = 3
print x
print y

[0 2]
[0 1 2 3 4]
[3 2]


In [22]:
# slicing creates a view
x = np.arange(5)
y = x[0:2]
y[0] = 3
print x
print y

[3 1 2 3 4]
[3 1]


In [23]:
x = np.arange(10)
mask = x <= 6
print mask
print x[mask]

[ True  True  True  True  True  True  True False False False]
[0 1 2 3 4 5 6]


Unfortunately, we can't chain logical operators as we can with built-in data types. You have to explicitly use NumPy's versions of the boolean operators.

In [24]:
mask1 = x <= 6
mask2 = x >= 3
mask3 = np.logical_and(mask1, mask2)
print mask1
print mask2
print mask3

[ True  True  True  True  True  True  True False False False]
[False False False  True  True  True  True  True  True  True]
[False False False  True  True  True  True False False False]


In [25]:
mask4 = np.logical_xor(mask1, mask2)
print mask4

[ True  True  True False False False False  True  True  True]


Boolean masks create a _copy_ of the data.

In [26]:
y = x[mask]
print x
print y
y[:] = 0
print x
print y

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8 9]
[0 0 0 0 0 0 0]


Another form of fancy indexing is using index arrays. I don't use this quite as often, but it can come in handy.

In [27]:
x = np.arange(24).reshape((4,-1))
print x
y = np.arange(x.shape[1])
print y

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 1 2 3 4 5]


In [28]:
i = np.random.permutation(y)
print i
print x[:,i]

[5 3 2 1 0 4]
[[ 5  3  2  1  0  4]
 [11  9  8  7  6 10]
 [17 15 14 13 12 16]
 [23 21 20 19 18 22]]


<h3>Broadcasting:</h3> <br>
A fancy name for the rules when applying operations to shapes of different shapes.

Typically, operations are performed element by element.

In [29]:
x = np.arange(10)
print x * x

[ 0  1  4  9 16 25 36 49 64 81]


But when we have arrays of different sizes...

In [30]:
y = x.reshape((1,-1))
print y

[[0 1 2 3 4 5 6 7 8 9]]


In [31]:
z = x.reshape((-1,1))
print z

print y.shape
print z.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(1, 10)
(10, 1)


In [32]:
x=np.arange(5).reshape(5,-1)
y = np.arange(4).reshape(-1,4)
z=x.reshape((1,-1))
print z
print x,y
print x+y
print x+x

[[0 1 2 3 4]]
[[0]
 [1]
 [2]
 [3]
 [4]] [[0 1 2 3]]
[[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
[[0]
 [2]
 [4]
 [6]
 [8]]


In [33]:
print y*y
print x@y
print x*z
print x.dot(z)
print np.dot(x,z)

SyntaxError: invalid syntax (<ipython-input-33-bbd2597a5f0e>, line 3)

The operation can be performed on every combination of elements from the two arrays.
Not essential for this class, but can be really handy in writing compact code for scientific computing.

## Imshow( ) and RGB color channels
Instead of using a single real number per pixel, for which we then need to find a colormap, we can also specify the color explicitly, using three channels (red, green and blue). If an array is n × m × 3, then imshow() interprets this as an image with RGB colors. The strength of each of the three colors is specified in the range [0,1]. For example, this is how we specify a 2 × 3 image, with colors red, green, blue, and purple, white, black:

In [ ]:
image=[[[1.0,0.0,0.0],[0.0,1,0.0],[0.0,0.0,1.0]],
       [[1.0,0.0,1.0],[1.0,1.0,1.0],[0.0,0.0,0.0]]]
plt.imshow(image)
plt.show()

We may also import image files, which are translated to arrays of this form, using the __matplotlib.image__ module.

In [ ]:
import matplotlib.image as mpimg 
img=mpimg.imread('kitty-cat.jpg')
plt.imshow(img)
plt.show()

In [ ]:
print type(img)
print img.ndim
print img.shape
print img.dtype

In [ ]:
img[100][100]